name: Node.js Package

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'dependabot/**'
  pull_request:
    branches:
      - main
      - 'feature/**'
      - 'dependabot/**'

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t nodepqcreader .

      - name: Run Docker container
        run: docker run --rm nodepqcreader

  build-npm-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: pqc-tracer
        run: npm install

      - name: Build npm package
        working-directory: pqc-tracer
        run: npm run build

  publish-npm-package:
    runs-on: ubuntu-latest
    needs: build-npm-package
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        working-directory: pqc-tracer
        run: npm install

      - name: Publish to npmjs
        working-directory: pqc-tracer
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
